import type { LucideIcon } from 'lucide-react';
import {
  Anchor, Apple, Award, Banana, Bell, Bike, Bomb, BookOpen, Brain,
  Briefcase, Cake, Camera, Car, Castle, Cat, Cherry, Cloud, Coffee,
  Diamond, Dog, Dices, Droplet, Feather, Film, Fish, Flag,
  Flame, Flower, Gift, Globe, Grape, Heart, Home, IceCream, KeyRound, 
  Leaf, Lightbulb, Lock, Map, Moon, MousePointer, Music, Package, 
  Palette, Paperclip, PenTool, Phone, Pizza, Plane, Puzzle, Rocket, 
  Settings2, Shield, Ship, ShoppingBag, Smile, Snowflake, Sparkles, Speaker, Star, Sun,
  Sword, Tag, Target, Tent, ThumbsUp, ToyBrick, Train, TreePine, Trophy, 
  Turtle, Umbrella, Utensils, Volume2, Wallet, Watch, Waves, Wind, Wine, Zap
} from 'lucide-react';

// A curated list of distinct and recognizable icons.
// We need at least `maxPairs` unique icons. If maxPairs is 18, we need 18 icons.
// Let's provide more to choose from, e.g., 36 unique icons for up to 36 pairs (72 cards), though UI will limit this.
// The generateCardSet function will slice this array based on numPairs.
export const gameIconsList: { name: string, component: LucideIcon }[] = [
  { name: 'Anchor', component: Anchor },
  { name: 'Apple', component: Apple },
  { name: 'Award', component: Award },
  { name: 'Banana', component: Banana },
  { name: 'Bell', component: Bell },
  { name: 'Bike', component: Bike },
  { name: 'Bomb', component: Bomb },
  { name: 'BookOpen', component: BookOpen },
  { name: 'Brain', component: Brain },
  { name: 'Briefcase', component: Briefcase },
  { name: 'Cake', component: Cake },
  { name: 'Camera', component: Camera },
  { name: 'Car', component: Car },
  { name: 'Castle', component: Castle },
  { name: 'Cat', component: Cat },
  { name: 'Cherry', component: Cherry },
  { name: 'Cloud', component: Cloud },
  { name: 'Coffee', component: Coffee },
  { name: 'Diamond', component: Diamond },
  { name: 'Dog', component: Dog },
  { name: 'Dices', component: Dices },
  { name: 'Droplet', component: Droplet },
  { name: 'Feather', component: Feather },
  { name: 'Film', component: Film },
  { name: 'Fish', component: Fish },
  { name: 'Flag', component: Flag },
  { name: 'Flame', component: Flame },
  { name: 'Flower', component: Flower },
  { name: 'Gift', component: Gift },
  { name: 'Globe', component: Globe },
  { name: 'Grape', component: Grape },
  { name: 'Heart', component: Heart },
  { name: 'Home', component: Home },
  { name: 'IceCream', component: IceCream },
  { name: 'KeyRound', component: KeyRound },
  { name: 'Leaf', component: Leaf },
  { name: 'Lightbulb', component: Lightbulb },
  { name: 'Lock', component: Lock },
  { name: 'Map', component: Map },
  { name: 'Moon', component: Moon },
  { name: 'MousePointer', component: MousePointer },
  { name: 'Music', component: Music },
  { name: 'Package', component: Package },
  { name: 'Palette', component: Palette },
  { name: 'Paperclip', component: Paperclip },
  { name: 'PenTool', component: PenTool },
  { name: 'Phone', component: Phone },
  { name: 'Pizza', component: Pizza },
  { name: 'Plane', component: Plane },
  { name: 'Puzzle', component: Puzzle },
  { name: 'Rocket', component: Rocket },
  { name: 'Settings2', component: Settings2 },
  { name: 'Shield', component: Shield },
  { name: 'Ship', component: Ship },
  { name: 'ShoppingBag', component: ShoppingBag },
  { name: 'Smile', component: Smile },
  { name: 'Snowflake', component: Snowflake },
  { name: 'Sparkles', component: Sparkles },
  { name: 'Speaker', component: Speaker },
  { name: 'Star', component: Star },
  { name: 'Sun', component: Sun },
  { name: 'Sword', component: Sword },
  { name: 'Tag', component: Tag },
  { name: 'Target', component: Target },
  { name: 'Tent', component: Tent },
  { name: 'ThumbsUp', component: ThumbsUp },
  { name: 'ToyBrick', component: ToyBrick },
  { name: 'Train', component: Train },
  { name: 'TreePine', component: TreePine },
  { name: 'Trophy', component: Trophy },
  { name: 'Turtle', component: Turtle },
  { name: 'Umbrella', component: Umbrella },
  { name: 'Utensils', component: Utensils },
  { name: 'Volume2', component: Volume2 },
  { name: 'Wallet', component: Wallet },
  { name: 'Watch', component: Watch },
  { name: 'Waves', component: Waves },
  { name: 'Wind', component: Wind },
  { name: 'Wine', component: Wine },
  { name: 'Zap', component: Zap },
];

// Ensure we have enough unique icons for typical game sizes
// Max number of pairs users can select, e.g., 18 pairs. So we need at least 18 unique icons.
// The list above has more than enough.
